# -*- coding: utf-8 -*-
"""clustering

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YWE6nuZSDDVKHLPypkyZk5c53PTaHx4T
"""

# This Jupyter notebook is prepared by Eoin Corcoran

"""# 1. EDA

I. Library Imports
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
import missingno as msno
import scipy.stats as st
import sklearn

from google.colab import drive 
drive.mount('/content/gdrive')

"""II. Data Import"""

df = pd.read_csv('/content/gdrive/MyDrive/Machine Learning/data/COVID_08312020.csv')
df.shape

"""III. Head/Tail"""

df.head()

df.tail()

"""IV. Null Values"""

df.isnull().sum().sort_values(ascending = False)

"""V. Column Types"""

df.info()

"""VI. Correlation Heatmap"""

correlation = df.corr()
sns.heatmap(correlation, annot = True)

"""# 2. Feature Selection and Preprocessing

I. X
"""

X = df.loc[:, 'city_development_index':'training_hours']

"""II. Feature Scaling"""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scale = pd.DataFrame(scaler.fit_transform(X))
X_scale.columns = X.columns

X_scale.head()

"""# KMeans Clustering

I. KMeans
"""

from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 2, init = 'k-means++', random_state = 47)
kmeans.fit(X_scale)

"""II. Clusters"""

kmeans.cluster_centers_

scaler.inverse_transform(kmeans.cluster_centers_)

"""The first cluster has its center where the city development index is 0.799, the size of the company has 100-500 employees, the individual has 6.62 years of experience, had their last new job 1.323 years ago, and completed 66.403 hours of training.

The second cluster has its center where the city development index is 0.889, the size of the company has 500-999 employees, the individual has 16.754 years of experience, had their last new job 3.727 years ago, and completed 64.694 hours of training.

III. Distance Matrix
"""

kmeans.transform(X_scale)

"""IV. Cluster Labels"""

kmeans.labels_

"""V. Cluster Labels Column"""

df['cluster_label'] = kmeans.labels_

"""VI. Target to Int"""

df['target_int'] = df['target'].apply(int)

"""VII. Changes"""

df.head()

"""VIII. Classification Evaluation"""

from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(df['target_int'], df['cluster_label']))

print(classification_report(df['target_int'], df['cluster_label']))

misclass = (df['target_int'] != df['cluster_label']).sum()
misclass

"""IX. Discussion of Evaluation

The confusion matrix shows that the model is much better at classifying targets of 0 than targets of 1. The model correctly identifies 77% of clusters with label 0, whereas it only correctly identifies 10% of clusters with label 1.

X. Inertia
"""

kmeans.inertia_

"""XII. n-clusters and inertia"""

inertias = []

for i in range(1, 21):
  kmean = KMeans(i, init = 'k-means++', random_state = 47)
  kmean.fit(X_scale)
  inertia_i = kmean.inertia_
  inertias.append(inertia_i)

num_clusters = range(1, 21)
plt.plot(num_clusters, inertias)
plt.title('Inertias')
plt.xlabel('Number of Clusters')
plt.ylabel('Inertia')
plt.show()

"""XIII. Scatterplot with Cluster Labels (training_hours and experience)"""

identified_clusters = kmeans.fit_predict(X_scale)
clusters_df = df.copy()
clusters_df['Clusters'] = identified_clusters 
plt.scatter(clusters_df['training_hours'], clusters_df['experience'], c = clusters_df['Clusters'], cmap='rainbow')

"""The plot above shows that the training_hours and experience variables are fairly successful in splitting the data into two even clusters. The red points are mostly confined to the top half of the plot (high experience) and the purple points are mostly in the bottom half of the plot (low experience).

XIV. Scatterplot with Cluster Labels (last_new_job and company_size)
"""

identified_clusters = kmeans.fit_predict(X_scale)
clusters_df = df.copy()
clusters_df['Clusters'] = identified_clusters 
plt.scatter(clusters_df['last_new_job'], clusters_df['company_size'], c = clusters_df['Clusters'], cmap='rainbow')

"""The plot above shows that the last_new_job and company_size variables are more successful in splitting the data into two even clusters. The red points are mostly confined to the right half of the plot (high time since last new job) and the purple points are mostly in the left half of the plot (low time since last new job). There is some overlap in both of these regions, but for the most part it is moderately homogenous.

# 4. Agglomerative Clustering

I. Dendrogram
"""

import scipy.cluster.hierarchy as shc
plt.figure(figsize = (10, 7))
plt.title('Dendrogram')

dend = shc.dendrogram(shc.linkage(X_scale, method = 'ward'))

"""II. Agglomerative Clustering - 2 clusters"""

from sklearn.cluster import AgglomerativeClustering
cluster = AgglomerativeClustering(n_clusters = 2, affinity = 'euclidean', linkage = 'ward')
cluster.fit_predict(X_scale)

"""III. Scatterplot with Cluster Labels (training_hours and experience)"""

plt.scatter(df['training_hours'], df['experience'], c = cluster.labels_)
plt.show()

"""This plot a little different than the one from 3.XIII since it mostly confines the top cluster from 3.XIII to the top left corner, while the bottom cluster moves to the rest of the plot.

IV. Agglomerative Clustering - 4 clusters
"""

from sklearn.cluster import AgglomerativeClustering
cluster = AgglomerativeClustering(n_clusters = 4, affinity = 'euclidean', linkage = 'ward')
cluster.fit_predict(X_scale)

plt.scatter(df['training_hours'], df['experience'], c = cluster.labels_)
plt.show()