# -*- coding: utf-8 -*-
"""nlp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uOPmnqa---DENJ6JWKqqyXCSdtfSlpU9
"""

# This Jupyter notebook is prepared by Eoin Corcoran

"""# 1. EDA

I. Library Imports
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
import missingno as msno
import scipy.stats as st
import sklearn
import string
import io

from google.colab import drive 
from google.colab import files

import nltk   
from wordcloud import WordCloud
from nltk.stem import WordNetLemmatizer 
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer

nltk.download()

"""II. Reading file"""

uploaded = files.upload()

news = [line.replace('"', '').rstrip().strip(',').split('\t') for line in open('news.csv')]

for article in news[:10]:
  print(article)
  print('\n')

"""III. Data Frame"""

df = pd.read_csv('news.csv', sep = '\t')
df

df.head()

"""IV. Null Values"""

df.isnull().sum().sort_values(ascending = False)

"""V. Countplot (news subject)"""

sns.countplot(df['subject'], data = df)
plt.xticks(rotation = 90)

"""VI. Countplot (real/fake)"""

sns.countplot(df['target'], data = df)

"""VII. Word Clouds"""

realdf = df.loc[df['target'] == 1]
fakedf = df.loc[df['target'] == 0]

realtext = ' '.join(cat for cat in realdf.text)
word_cloud = WordCloud(collocations = False, background_color = 'white').generate(realtext)
plt.imshow(word_cloud, interpolation = 'bilinear')
plt.axis('off')
plt.show()

faketext = ' '.join(cat for cat in fakedf.text)
fake_word_cloud = WordCloud(collocations = False, background_color = 'white').generate(faketext)
plt.imshow(fake_word_cloud, interpolation = 'bilinear')
plt.axis('off')
plt.show()

"""The fake news articles tend to mention Trump, and more proper names in general, a lot more than real news articles. "said" is a popular word among both fake and real news articles, but "new" is more prevalent in fake news articles. Real news articles also have more words like "government" and "state" than the fake counterparts.

VIII. AllText column
"""

cols = ['subject', 'title', 'text']
df['allText'] = df[cols].apply(lambda row: '_'.join(row.values.astype(str)), axis = 1)

"""IX. Copy"""

df2 = df.copy()

"""X. Dropping Variables"""

df2.drop(['title', 'text', 'subject', 'date'], axis = 1, inplace = True)

"""XI. Length of Text"""

df2['length'] = df2['allText'].apply(len)

"""XII. Histograms of Length"""

realdf2 = df2.loc[df2['target'] == 1]
fakedf2 = df2.loc[df2['target'] == 0]

plt.hist(realdf2['length'])
plt.show()

plt.hist(fakedf2['length'])
plt.show()

"""The fake news articles do not have as much variance as the real news articles do, as most of the fake news articles are between 0 and 5000 words, while most of the real news articles are between 0 and about 2500 words. However, a good amount of real news articles are also between 2500 and 5000 words as well, showing the varying length they can have.

#2. Train-Test Split

I. Splitting Data
"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df2['allText'], df2['target'], test_size = 0.2, random_state = 0)

"""II. Countplot (real/fake)"""

sns.countplot(y_train)
plt.show()

sns.countplot(y_test)
plt.show()

"""#3. MultinomialNB

I. Pipeline
"""

from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

stemmer = LancasterStemmer() 

def text_process(mess):
    stopwordList = stopwords.words('english')

    mess = [char for char in mess if char not in string.punctuation]
    mess = ''.join(mess)

    words = nltk.word_tokenize(mess)
    words = [t for t in words if t not in stopwordList]
    words = [stemmer.stem(w.lower()) for w in words]

    return words

pipeline = Pipeline([('BoW', CountVectorizer(analyzer = text_process)),
                     ('tfidf', TfidfTransformer()),
                     ('classifier', MultinomialNB(alpha = 1.5))])

"""II. Fitting/Predicting"""

pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)

"""III. Evaluation"""

from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

"""IV. Discussion

This model obtained accuracy of 96% and was very good in classifying both fake and real news articles, as shown by the precision of 95% and 96% respectively. It only misclassified 404 observations, 170 of which are false negatives and 234 are false positives, so it is slightly better at predicting real news.

V. News Prediction
"""

article = ["According to the book, Biden, who told audience members at the town hall he was uninterested in forgiving 'the billions of dollars in debt for people who have gone to Harvard and Yale and Penn,' seemingly associated 'hefty debts with fancy universities.' Biden's comments sent his staff, including chief of staff Ron Klain, into a spiral as they attempted to alter what the president said in an effort to appease the progressive wing of the party. That wing had been calling for him to forgive more than the $10,000 he had originally promised, the authors explained. Despite Biden's own remarks, Klain, according to the book, spoke in private 'with several congressional supporters of debt cancellation to assure them his boss had not intended to take such a firm position." "One lawmaker who spoke with Ron Klain recalled him saying gently that sometimes Biden gets a little tangled up in his public statements,' the authors wrote. 'When a group of House progressives raised the subject again with Klain in a meeting several weeks later, the trusted aide alluded to Biden's comments as an error.'"]
article_pred = pipeline.predict(article)

article_pred

"""#4. Deep Neural Network

I. Library
"""

from sklearn.neural_network import MLPClassifier

"""II. Pipeline"""

pipelineMLP = Pipeline([('BoW', CountVectorizer(analyzer = text_process)),
                     ('tfidf', TfidfTransformer()),
                     ('classifier', MLPClassifier(hidden_layer_sizes = (100, 3), verbose = 2, early_stopping = True, random_state = 0))])

"""III. Fitting/Predicting"""

pipelineMLP.fit(X_train, y_train)

y_predMLP = pipelineMLP.predict(X_test)

"""IV. Evaluation"""

print(confusion_matrix(y_test, y_predMLP))

print(classification_report(y_test, y_predMLP))

"""V. Discussion

The neural network model was excellent in predicting real and fake news, with almost 100% accuracy. It only misclassified 34 observations, 23 of which were false positives and 11 of which were false negatives, so it was slightly better at predicting fake news. The precision and recall scores as shown in the classification report, are almost 100% as well for both classes, further demonstrating the power of this model.

VI. News Prediction
"""

article_predMLP = pipelineMLP.predict(article)
article_predMLP

"""VIII. Discussion (MLP vs NB)

The neural network model definitely outperformed the MultinomialNB model by almost 4% accuracy and 370 less misclassifications. However, the neural network model took much longer to run and is not as simple as the MultinomialNB model.

# Predicting Subject of News
"""

df_ec = pd.read_csv('news.csv', sep = '\t')

# creating subject variable for use in predicting
df_ec['subject'] = df_ec['subject'].map({'politicsNews': 0,
                                         'worldnews': 1,
                                         'News': 2,
                                         'politics': 0,
                                         'Government News': 3,
                                         'left-news': 4,
                                         'US_News': 5,
                                         'Middle-east': 6})

# showing counts of each subject 
sns.countplot(df_ec['subject'])
plt.show()

# cleaning up text
cols = ['title', 'text']
df_ec['allText'] = df_ec[cols].apply(lambda row: '_'.join(row.values.astype(str)), axis = 1)

df_ec.drop(['title', 'text', 'date', 'target'], axis = 1, inplace = True)

df_ec.head()

# creating train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_ec['allText'], df_ec['subject'], test_size = 0.25, random_state = 0)

# creating pipeline for fitting model - uses tfidf and bag of words techniques and neural network classifier
pipelineMLP_ec = Pipeline([('BoW', CountVectorizer(analyzer = text_process)),
                     ('tfidf', TfidfTransformer()),
                     ('classifier', MLPClassifier(hidden_layer_sizes = (100, 3), verbose = 2, early_stopping = True, random_state = 0))])

pipelineMLP_ec.fit(X_train, y_train)

y_pred_ec = pipelineMLP_ec.predict(X_test)

print(confusion_matrix(y_test, y_pred_ec))

print(classification_report(y_test, y_pred_ec))

"""The model does very poorly at predicting Government News, US News, and left news, most likely due to the small amount of observations for US News and Government News. However, the model is good at predicting political news, world news, and news, likely due to the large amount of observations present in these categories. Political news and other categories likely overlap with a lot of other categories, so further investigation is required to increase the accuracy. This model could also be improved through hyperparameter tuning of the neural network, although getting a better idea of the data and news categories would likely be better."""