# -*- coding: utf-8 -*-
"""xgboost.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gPPbH3zMieaOfP_aqCICOAI3R0EnCrrj
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import numpy.random as random
import xgboost as xgb
import numpy.random as rand
import scipy.stats as stats
import haversine as hvs
import math as m
import geopy.distance as dist
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, RandomizedSearchCV, GridSearchCV, cross_validate
from pyproj import Proj, transform

from google.colab import drive 
drive.mount('/content/gdrive')

df = pd.read_csv('/content/gdrive/MyDrive/Business Analytics/sales.csv')
random.seed(1234)
df = df.sample(len(df))

from google.colab import drive 
drive.mount('/content/gdrive')

val_set = pd.read_csv('/content/gdrive/MyDrive/Business Analytics/validation_set.csv')
random.seed(1234)
val_set = val_set.sample(len(val_set))

from google.colab import drive 
drive.mount('/content/gdrive')

df = pd.read_csv('/content/gdrive/MyDrive/sales.csv')

random.seed(1234)
df = df.sample(len(df))

inProj = Proj(init='epsg:2236', preserve_units = True)
outProj = Proj(init='epsg:4326')

x, y = df['x_coord'], df['y_coord']
df['long'], df['lat'] = transform(inProj, outProj, x, y)

inProj = Proj(init='epsg:2236', preserve_units = True)
outProj = Proj(init='epsg:4326')

x, y = val_set['x_coord'], val_set['y_coord']
val_set['long'], val_set['lat'] = transform(inProj, outProj, x, y)

long_list = df['long'].values.tolist()
long_list

lat_list = df['lat'].values.tolist()
lat_list

# adding distance variables
df['area_ratio'] = df['home_size'] / df['parcel_size']

disney_lat = 28.38154
disney_long = -81.57034
airport_lat = 28.41776
airport_long = -81.30396

disney = (28.38154, -81.57034)
airport = (28.41776, -81.30396)

lat_list = df['lat'].values.tolist()
long_list = df['long'].values.tolist()

disney_distances = []
airport_distances = []

for i in range(0, 10000):
  home = (lat_list[i], long_list[i])
  disney_distances.append(hvs.haversine(disney, home))
  airport_distances.append(hvs.haversine(airport, home))

df['dist_disney'] = disney_distances
df['dist_airport'] = airport_distances

disney_list = df['dist_disney'].values.tolist()
disney_list

# creating and naming variables for better organization
df['age'] = df['age'] + 0.01
z = df[['home_size', 'parcel_size', 'beds', 'age', 'pool', 'cbd_dist', 'dist_airport', 'dist_disney', 'area_ratio']]

variables = {}
for variable in z.columns.values:
    var = z[variable] ** 2
    variables["{0}_2".format(variable)] = var 
    z['{0}_2'.format(variable)] = pd.Series(dtype=int, data = variables['{0}_2'.format(variable)])
    
    var = z[variable] ** 3
    variables["{0}_3".format(variable)] = var 
    z['{0}_3'.format(variable)] = pd.Series(dtype=int, data = variables['{0}_3'.format(variable)])

    var = np.log(np.abs(z[variable]))
    variables["{0}_log".format(variable)] = var 
    z['{0}_log'.format(variable)] = pd.Series(dtype=int, data = variables['{0}_log'.format(variable)])

    var = np.sqrt(np.abs(z[variable]))
    variables["{0}_sqrt".format(variable)] = var 
    z['{0}_sqrt'.format(variable)] = pd.Series(dtype= int, data = variables['{0}_sqrt'.format(variable)])

    var = z[variable] ** -1.0
    variables["{0}_inv".format(variable)] = var 
    z['{0}_inv'.format(variable)] = pd.Series(dtype=int, data = variables['{0}_inv'.format(variable)])

    var = z[variable] ** -0.5
    variables["{0}_invsqrt".format(variable)] = var 
    z['{0}_invsqrt'.format(variable)] = pd.Series(dtype=int, data = variables['{0}_invsqrt'.format(variable)])

x = z[['home_size', 'age', 'home_size_2', 'dist_disney_2', 'dist_airport_sqrt', 'dist_airport', 'dist_disney_sqrt', 'dist_disney_invsqrt', 'parcel_size', 'parcel_size_log', 'cbd_dist', 'home_size_sqrt', 'dist_disney_log', 'age_2', 'home_size_log', 'pool', 'age_sqrt', 'cbd_dist_2']]
y = df.Price

# standardizing the predictor variables
pipe = Pipeline(steps = [('scale', StandardScaler())])

x_train, x_test, y_train, y_test = train_test_split(x_processed, y, test_size = 0.1, random_state = 100)

x_processed = pipe.fit_transform(x)

param_grid = {
    "max_depth": [5],           # maximum depth of a tree - increasing this will make model fitting take a lot longer and more likely to overfit
    "learning_rate": [0.4],     # step size shrinkage used in update to prevents overfitting (default is 0.3, cannot be more than 1)
    "gamma": [0],               # minimum loss reduction required to make a further partition on a leaf node of the tree (must be > 0)
    "subsample": [0.8],         # randomly sample (subsample * 100)% of the training data prior to growing trees (must be <= 1)
    "colsample_bytree": [0.5] }

'''
############################### BEST MODEL
 "['home_size', 'age', 'home_size_2', 'dist_disney_2', 'dist_airport_sqrt', 'dist_airport', 'dist_disney_sqrt', 'dist_disney_invsqrt', 'parcel_size', 'parcel_size_log', 'cbd_dist', 'home_size_sqrt', 'dist_disney_log', 'age_2', 'home_size_log', 'pool', 'age_sqrt', 'cbd_dist_2']": [5598.07288624494,
  {'colsample_bytree': 0.5,
  'gamma': 0,
  'lambda': 0,
  'learning_rate': 0.4,
  'max_depth': 5,
  'subsample': 0.8}
'''

'''
"['beds_inv', 'dist_disney_2', 'dist_disney_log', 'home_size_2', 'dist_airport_invsqrt', 'cbd_dist_2', 'home_size', 'home_size_log', 'cbd_dist_log', 'dist_airport_sqrt', 'cbd_dist', 'pool', 'home_size_inv', 'age', 'dist_airport_log', 'parcel_size_inv', 'parcel_size', 'age_2']": [-6068.326159478923,
  {'colsample_bytree': 0.5,
   'gamma': 1,
   'lambda': 0,
   'learning_rate': 0.1,
   'max_depth': 7,
   'subsample': 0.5}],
'''

'''
################################## IMPROVED MODEL
{'alpha': 0,
 'colsample_bytree': 0.5,
 'gamma': 0,
 'lambda': 0,
 'learning_rate': 0.1,
 'max_depth': 6,
 'subsample': 0.5}

 test MSE: 5836.676916304945 (home, parcel, age, cbd, pool, disney, airport, home2, cbd2, cbd3, inv_age, sqrt_airport, sqrt_disney)
'''

'''

{'colsample_bytree': 0.5,
 'gamma': 6,
 'learning_rate': 0.2,
 'max_depth': 6,
 'reg_lambda': 2.5,
 'subsample': 0.7}
 
 test MSE: 6376.3405011135355 (home, parcel, age, cbd, disney, home2)
'''

'''
#################################### BASIC MODEL 
{'colsample_bytree': 0.5,
 'gamma': 1,
 'learning_rate': 0.1,
 'max_depth': 5,
 'reg_lambda': 1,
 'subsample': 0.8}

 test MSE: 9281.15562358389 (home, parcel, beds, age, pool, cbd, airport)
'''

'''
{'colsample_bytree': 0.5,
 'gamma': 3,
 'learning_rate': 0.3,
 'max_depth': 5,
 'reg_lambda': 0,
 'subsample': 1}

 test MSE: 7067.433181867475 (home, parcel, beds, age, pool, cbd, airport)
 '''

'''
{'colsample_bytree': 0.5,
 'gamma': 5,
 'learning_rate': 0.3,
 'max_depth': 5,
 'reg_lambda': 0,
 'subsample': 1}
(these look like the best parameters so far - at least for the variables listed)

 test MSE: 7063.900782817169 (home, parcel, beds, age, pool, cbd, airport)
'''

'''
{'colsample_bytree': 0.5,
 'gamma': 3,
 'learning_rate': 0.3,
 'max_depth': 4,
 'reg_lambda': 1,
 'subsample': 1}

 test MSE: 9094.988620490289 (home, parcel, beds, age, cbd, airport)
'''

'''
{'colsample_bytree': 0.5,
 'gamma': 3,
 'learning_rate': 0.4,
 'max_depth': 6,
 'reg_lambda': 1,
 'subsample': 0.9}

 test MSE: 7142.892510550785 (home, parcel, beds, age, pool, cbd, disney, airport, home2)
'''

xgb_reg = xgb.XGBRegressor(objective = 'reg:squarederror', colsample_bytree = 0.5, gamma = 0, learning_rate = 0.4, max_depth = 5, subsample = 0.8)

model = GridSearchCV(xgb_reg, param_grid, n_jobs = -1, cv = 10, scoring = 'neg_mean_squared_error')

# this is only to get train and test MSE and R2
xgbCV = cross_validate(xgb_reg, x_processed, y, cv = 10, scoring = ('neg_mean_squared_error', 'r2'), return_train_score = True)

xgbCV

train_MSE = -np.mean(xgbCV['train_neg_mean_squared_error'])
test_MSE = -np.mean(xgbCV['test_neg_mean_squared_error'])
train_R2 = np.mean(xgbCV['train_r2'])
test_R2 = np.mean(xgbCV['test_r2'])

print(train_MSE, test_MSE, train_R2, test_R2)

xgb_reg.fit(x_train, y_train)

pred = xgb_reg.predict(x_test)

final_MSE = sum((y_test - pred) ** 2) / len(y)
round(final_MSE, 2)

plt.scatter(pred, y_test)

# returns the lowest MSE across all models tested
model.best_score_

# returns parameters associated with lowest MSE
model.best_params_

def select(num_var):
  # creating four different combinations of variables to reduce amount of times python may need to recursively call this function
  varset1 = []
  varset2 = []
  varset3 = []
  varset4 = []

  # populating varset lists
  for j in range(0, 4):
    nums = []
    for k in range(0, (num_var % len(other_vars))): # picking variables for varsets
      randnum = random.randint(1, len(other_vars))
      nums.append(other_vars[randnum])
    
    # control flow to guide nums list to its proper location
    if j == 0:
      for l in range(0, len(nums)):
        varset1.append(nums[l])
    elif j == 1:
      for l in range(0, len(nums)):
        varset2.append(nums[l])   
    elif j == 2:
      for l in range(0, len(nums)):
        varset3.append(nums[l])
    elif j == 3:
      for l in range(0, len(nums)):
        varset4.append(nums[l])

  # make sure to check if combos_tested is only one nested list - [[home, parcel], [beds, pool, cbd]] vs [[[home, parcel]], [[beds, pool, cbd]]]
  for item, a in enumerate(combos_tested):
    if varset1 == item:
      varset1 = []
    if varset2 == item:
      varset2 = []
    if varset3 == item:
      varset3 = []
    if varset4 == item:
      varset4 = []

  # checking if all of the varsets are of length 0 (meaning they had a combo of variables already in combos_tested)
  if len(varset1) == len(varset2) == len(varset3) == len(varset4) == 0:
    select(num_var)
  # returning the first varset that is not of length 0
  elif len(varset1) != 0:
    return varset1
  elif len(varset2) != 0:
    return varset2
  elif len(varset3) != 0:    
    return varset3
  elif len(varset4) != 0:   
    return varset4

other_vars = ['beds', 'dist_disney', 'dist_airport', 'home_size_2', 'parcel_size_2', 'beds_2', \
      'age_2', 'cbd_dist_2', 'dist_airport_2', 'dist_disney_2', 'home_size_sqrt', \
      'parcel_size_sqrt', 'age_sqrt', 'cbd_dist_sqrt', 'dist_disney_sqrt', 'dist_airport_sqrt', \
      'home_size_log', 'parcel_size_log', 'age_log', 'cbd_dist_log', 'dist_disney_log', 'dist_airport_log', \
      'home_size_inv', 'parcel_size_inv', 'beds_inv', 'cbd_dist_inv', 'dist_disney_inv', 'dist_airport_inv', \
      'home_size_invsqrt', 'parcel_size_invsqrt', 'beds_invsqrt', 'cbd_dist_invsqrt', 'dist_disney_invsqrt', 'dist_airport_invsqrt']

count = 0

while(count < 7):
  combinations = []
  selection = ['home_size', 'parcel_size', 'age', 'pool', 'cbd_dist']
  
  if count == 0:
    random_dict = {}
    models = {}
    params = {}

  numvar = random.randint(3, len(other_vars)) # controls how many variables are in each model (approximately)
  more_vars = select(numvar)

  for i in range(0, len(more_vars)):
    selection.append(more_vars[i])
  
  random_dict[count] = list(set(selection))
  
  combinations.append(random_dict[count])
  x = z[list(random_dict[count])]
  y = df['Price']
      
  pipe = Pipeline(steps = [('scale', StandardScaler())])    
  x_processed = pipe.fit_transform(x)
  
  param_grid = {
      "max_depth": [5, 6, 7],           
      "learning_rate": [0.1, 0.2, 0.3], 
      "gamma": [0, 1],               
      "lambda": [0, 10],                
      "subsample": [0.5, 0.8],       
      "colsample_bytree": [0.5] }
  
  xgb_reg = xgb.XGBRegressor (objective = 'reg:squarederror')
  model = GridSearchCV(xgb_reg, param_grid, n_jobs = -1, cv = 10, scoring = 'neg_mean_squared_error')
  model.fit(x_processed, y)

  best_mse = model.best_score_
  best_params = model.best_params_
  mean_score = models.cv_results_["mean_test_score"][grid.best_index_]

  models[str(random_dict[count])] = [mean_score, best_params]

  combos_tested.append(combinations)

  count += 1

  # models dict will be overwritten when you run this cell again!!! 
  # make sure you look at models produced by running cell below and seeing if there are any low MSEs - can also try tuning parameters for that model

models